import type { Config } from './config.js';
import { scopeLabels } from './config.js';
export const escape = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
const css = `:root{color-scheme:light;font-family:system-ui,sans-serif;color:#17382a;background:#f4f8f3}*{box-sizing:border-box}body{margin:0}main{max-width:760px;margin:7vh auto;padding:32px}header{display:flex;align-items:center;gap:12px;margin-bottom:32px}header svg{width:38px;height:38px}h1{font-size:clamp(28px,6vw,44px);line-height:1.1;letter-spacing:-1px;margin:10px 0 18px}h2{font-size:20px}p{line-height:1.6;color:#465f50}a{color:#17623c}small{color:#526a5b}.card{background:#fff;border:1px solid #d9e5d9;border-radius:18px;padding:26px;margin:22px 0;box-shadow:0 6px 24px #17382a06}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:2px;font-weight:700;color:#42744e}.button,button{display:inline-block;border:0;border-radius:9px;background:#1e643c;color:white;font:inherit;font-weight:650;text-decoration:none;padding:13px 19px;cursor:pointer}.secondary{background:#e7eee5;color:#17382a}label{display:block;font-weight:600;margin:18px 0 8px}input[type=password],input[type=text]{width:100%;border:1px solid #adbfaf;border-radius:8px;padding:12px;font:inherit}input[type=checkbox]{margin-right:10px}code{font-size:13px;overflow-wrap:anywhere;background:#eaf1e7;border-radius:5px;padding:3px 5px}ul,ol{padding-left:24px;line-height:1.9}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:24px}.notice{background:#f4f1de;border-radius:9px;padding:14px;color:#685d23}.error{background:#fff0ef;border-radius:9px;padding:14px;color:#842e2e}footer{font-size:13px;margin-top:28px;color:#526a5b}footer a{margin-right:14px}:focus-visible{outline:3px solid #dfa31a;outline-offset:3px}@media(max-width:600px){main{margin:0;padding:22px}.card{padding:19px}}`;
export function page(title: string, body: string, metadata = '') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="same-origin"><title>${escape(title)} · Edworking MCP</title>${metadata}<style>${css}</style></head><body><main><header><svg viewBox="0 0 40 40" aria-hidden="true"><rect width="40" height="40" rx="12" fill="#21643b"/><path d="M27 11H13v18h14M13 20h11" fill="none" stroke="white" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg><strong>Edworking MCP</strong></header>${body}<footer><a href="/">Overview</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="https://github.com/Edworking/edworking-mcp">Source & support</a></footer></main></body></html>`;
}
export function landing(config: Config) {
  const description = 'Connect your AI assistant to Edworking projects, tasks, conversations and files with scoped OAuth access.';
  return page('Your work, connected', `<div class="eyebrow">The official Edworking MCP server</div><h1>Your workspace.<br>In the conversation.</h1><p>Bring Edworking into your AI assistant. Find the right task, catch up on a conversation, and turn a request into progress without losing the context of your work.</p><div class="actions"><a class="button" href="#connect">Connect your assistant</a><a class="button secondary" href="https://github.com/Edworking/edworking-mcp">Explore the open source project</a></div><div class="card"><h2>From questions to action</h2><ul><li><strong>Get context.</strong> Read accessible projects, task details, conversations and file information.</li><li><strong>Move work forward.</strong> Create projects and tasks, edit task names and deadlines, and send the messages you request.</li><li><strong>Choose access.</strong> Start with read permissions. Enable write permissions when you need them.</li></ul></div><div class="card" id="connect"><h2>Connect Edworking MCP</h2><p>In a compatible assistant, add a remote MCP server with OAuth using this URL:</p><p><code>${escape(config.resource)}</code></p><ol><li>Start the connection from your assistant and review its requested permissions.</li><li>In Edworking, open <strong>Profile → API tokens</strong> and create a dedicated token with those permissions.</li><li>Enter the token in the browser authorization page, then review and approve the connection.</li></ol><p>Keep the token out of chat. Your assistant receives a separate OAuth credential. Revoke the dedicated token in Edworking to stop access.</p><p><small>Requires an Edworking account and an assistant supporting Streamable HTTP and OAuth. Client availability and organization policies may vary.</small></p></div><h2>Try it with your work</h2><ul><li>“Show the tasks in my launch project.”</li><li>“Create a task to review the proposal, due Friday.”</li><li>“Read the latest messages in Demo planning.”</li></ul><p><small>Task search covers titles in up to 500 recently updated tasks. Document bodies, status changes, reassignment and deletion are not currently supported.</small></p><div class="actions"><a class="button" href="https://github.com/Edworking/edworking-mcp#readme">Setup and tool reference</a><a class="button secondary" href="${escape(config.appUrl)}">Open Edworking</a></div>`, `<meta name="description" content="${escape(description)}"><meta property="og:title" content="Edworking MCP"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${escape(config.origin)}/"><link rel="canonical" href="${escape(config.origin)}/">`);
}
export interface ConsentView { id: string; csrf: string; linkNonce: string; clientName: string; redirect: string; scopes: string[]; name?: string; expiresAt?: string; }
export function consent(config: Config, p: ConsentView, error?: string) {
  const fields = `<input type="hidden" name="request" value="${escape(p.id)}"><input type="hidden" name="csrf" value="${escape(p.csrf)}">`;
  const client = `<div class="eyebrow">Authorize a connection</div><h1>Connect Edworking</h1><p><strong>${escape(p.clientName)}</strong> is requesting access. Its callback destination is <strong>${escape(new URL(p.redirect).host)}</strong>.</p><p><small>The application name is supplied by the client. Approve only if you started this connection and recognize the destination.</small></p>`;
  const permissions = `<ul>${p.scopes.map(s => `<li>${escape(scopeLabels[s] || s)}</li>`).join('')}</ul>`;
  const failure = error ? `<p class="error" role="alert">${escape(error)}</p>` : '';
  if (p.name) return page('Review connection', `${client}${failure}<div class="card"><h2>Review access</h2><p>Connection: <strong>${escape(p.name)}</strong></p><p>Edworking credential expires: ${escape(p.expiresAt || '')}</p>${permissions}<p>This assistant can use only these permissions and the workspace attached to this connection.</p><form method="post" action="/oauth/approve">${fields}<div class="actions"><button name="decision" value="approve">Allow access</button><button class="secondary" name="decision" value="deny">Cancel</button></div></form></div>`);
  let native = '';
  if (config.connectUrl) {
    const url = new URL(config.connectUrl); url.searchParams.set('request', p.id); url.searchParams.set('nonce', p.linkNonce);
    native = `<a class="button" href="${escape(url.href)}">Continue in Edworking</a><p>Sign in, select your workspace, and approve the connection in Edworking.</p><details><summary>Connect with an existing API token instead</summary>`;
  }
  return page('Connect workspace', `${client}${failure}<div class="card"><h2>Requested permissions</h2>${permissions}${native}<p>In Edworking, open <strong>Profile → API tokens</strong> and create a dedicated token with the permissions above. Paste it here once. Your assistant receives a separate OAuth credential; it never receives this API token.</p><form method="post" action="/oauth/link-token" autocomplete="off">${fields}<label for="api-token">Edworking API token</label><input id="api-token" name="api_token" type="password" required maxlength="128" autocomplete="off" spellcheck="false" pattern="edw_pat_[A-Za-z0-9_-]{43}"><div class="actions"><button>Review connection</button><a class="button secondary" href="${escape(config.appUrl)}" target="_blank" rel="noopener noreferrer">Open Edworking</a></div></form>${config.connectUrl ? '</details>' : ''}</div><form method="post" action="/oauth/approve">${fields}<button class="secondary" name="decision" value="deny">Cancel connection</button></form>`);
}
export function privacy() { return page('Privacy', `<h1>Edworking MCP privacy</h1><p>Edworking MCP is Edworking’s connection service for MCP-compatible assistants.</p><div class="card"><h2>Data used for your connection</h2><p>We store OAuth client configuration, permission grants, credential expiry, and an encrypted Edworking API token. OAuth access and refresh tokens are stored as hashes. Your assistant receives the results of the tools you authorize, which can include project and task information, conversation content, participant names, and file metadata.</p><h2>Retention and control</h2><p>Connection records expire no later than the underlying Edworking API token. Cached mutation results are encrypted and retained for up to 24 hours to prevent duplicate writes. Expired records are removed periodically. Request logs contain operation names, timing, and outcomes, not credentials, message bodies, or tool results.</p><p>Revoke the dedicated connection token in Edworking’s Profile → API tokens to stop access. Your assistant provider controls the conversation history it stores. Contact Edworking through its website for privacy requests.</p><p><a href="https://edworking.com">Edworking website and support</a></p></div>`); }
export function terms() { return page('Terms', `<h1>Using Edworking MCP</h1><div class="card"><p>Edworking MCP connects your existing Edworking account to an assistant you choose. Your Edworking account terms and access permissions continue to apply. Review the assistant provider’s terms and data handling before connecting.</p><p>Only authorize clients you trust. Sending messages, creating projects, and uploading files can affect other people in your workspace. Describe the intended destination and action clearly.</p><p>The source code is provided under the MIT license. Hosted availability and supported tools can change; release notes are published in the repository.</p><a href="https://edworking.com">Edworking account and support information</a></div>`); }
